services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    restart: on-failure
    ports:
      - '8080:8080'
    develop:
      watch:
        - path: ./
          action: rebuild
          target: /app